import { db, uid, nowSec } from "./db";

// 500 beginner–intermediate French words (front) with Spanish meanings (back).
// Nouns include their article (le/la/l') — gender is essential in French.
const WORDS: Array<[string, string]> = [
  // Saludos y cortesía (20)
  ["bonjour", "buenos días / hola"],
  ["bonsoir", "buenas noches (saludo)"],
  ["bonne nuit", "buenas noches (despedida)"],
  ["salut", "hola / adiós (informal)"],
  ["au revoir", "adiós"],
  ["à bientôt", "hasta pronto"],
  ["s'il vous plaît", "por favor"],
  ["s'il te plaît", "por favor (informal)"],
  ["merci", "gracias"],
  ["merci beaucoup", "muchas gracias"],
  ["de rien", "de nada"],
  ["pardon", "perdón"],
  ["excusez-moi", "disculpe"],
  ["oui", "sí"],
  ["non", "no"],
  ["d'accord", "de acuerdo"],
  ["bienvenue", "bienvenido"],
  ["félicitations", "felicidades"],
  ["bon courage", "mucho ánimo"],
  ["à demain", "hasta mañana"],
  // Familia y personas (30)
  ["la famille", "la familia"],
  ["l'homme", "el hombre"],
  ["la femme", "la mujer"],
  ["l'enfant", "el niño / la niña"],
  ["le père", "el padre"],
  ["la mère", "la madre"],
  ["le fils", "el hijo"],
  ["la fille", "la hija"],
  ["le frère", "el hermano"],
  ["la sœur", "la hermana"],
  ["le grand-père", "el abuelo"],
  ["la grand-mère", "la abuela"],
  ["l'oncle", "el tío"],
  ["la tante", "la tía"],
  ["le cousin", "el primo"],
  ["la cousine", "la prima"],
  ["le mari", "el marido"],
  ["l'épouse", "la esposa"],
  ["le bébé", "el bebé"],
  ["l'ami", "el amigo"],
  ["l'amie", "la amiga"],
  ["le voisin", "el vecino"],
  ["la voisine", "la vecina"],
  ["le collègue", "el colega"],
  ["l'invité", "el invitado"],
  ["le monsieur", "el señor"],
  ["la dame", "la señora"],
  ["le garçon", "el chico"],
  ["les gens", "la gente"],
  ["le monde", "el mundo"],
  // Casa y hogar (40)
  ["la maison", "la casa"],
  ["l'appartement", "el apartamento / el piso"],
  ["la porte", "la puerta"],
  ["la fenêtre", "la ventana"],
  ["le mur", "la pared"],
  ["le toit", "el tejado"],
  ["le sol", "el suelo"],
  ["le salon", "la sala"],
  ["la cuisine", "la cocina"],
  ["la chambre", "la habitación"],
  ["la salle de bain", "el baño"],
  ["les toilettes", "el baño"],
  ["le lit", "la cama"],
  ["la table", "la mesa"],
  ["la chaise", "la silla"],
  ["le fauteuil", "el sillón"],
  ["le canapé", "el sofá"],
  ["l'armoire", "el armario"],
  ["le placard", "el armario (empotrado)"],
  ["l'étagère", "el estante"],
  ["le miroir", "el espejo"],
  ["la lampe", "la lámpara"],
  ["le rideau", "la cortina"],
  ["le tapis", "la alfombra"],
  ["la couverture", "la manta"],
  ["l'oreiller", "la almohada"],
  ["le drap", "la sábana"],
  ["la clé", "la llave"],
  ["la télé", "la tele"],
  ["l'ordinateur", "el ordenador / la computadora"],
  ["le téléphone", "el teléfono"],
  ["la machine à laver", "la lavadora"],
  ["le frigo", "la nevera / el refrigerador"],
  ["le four", "el horno"],
  ["la douche", "la ducha"],
  ["le savon", "el jabón"],
  ["la serviette", "la toalla"],
  ["le jardin", "el jardín"],
  ["le balcon", "el balcón"],
  ["le garage", "el garaje"],
  // Comida y bebida (50)
  ["le pain", "el pan"],
  ["l'eau", "el agua"],
  ["le lait", "la leche"],
  ["le café", "el café"],
  ["le thé", "el té"],
  ["le jus", "el zumo / el jugo"],
  ["le vin", "el vino"],
  ["la bière", "la cerveza"],
  ["le fromage", "el queso"],
  ["l'œuf", "el huevo"],
  ["la viande", "la carne"],
  ["le poisson", "el pescado"],
  ["le poulet", "el pollo"],
  ["le riz", "el arroz"],
  ["les pâtes", "la pasta"],
  ["la pomme", "la manzana"],
  ["la banane", "el plátano / la banana"],
  ["l'orange", "la naranja"],
  ["le citron", "el limón"],
  ["la fraise", "la fresa"],
  ["le raisin", "la uva"],
  ["la tomate", "el tomate"],
  ["la pomme de terre", "la patata / la papa"],
  ["la carotte", "la zanahoria"],
  ["l'oignon", "la cebolla"],
  ["la salade", "la ensalada"],
  ["le sel", "la sal"],
  ["le sucre", "el azúcar"],
  ["le poivre", "la pimienta"],
  ["l'huile", "el aceite"],
  ["le beurre", "la mantequilla"],
  ["le gâteau", "el pastel"],
  ["le chocolat", "el chocolate"],
  ["la glace", "el helado"],
  ["le petit-déjeuner", "el desayuno"],
  ["le déjeuner", "el almuerzo"],
  ["le dîner", "la cena"],
  ["le repas", "la comida"],
  ["le restaurant", "el restaurante"],
  ["le menu", "el menú / la carta"],
  ["l'addition", "la cuenta"],
  ["le serveur", "el camarero / el mesero"],
  ["la serveuse", "la camarera / la mesera"],
  ["le couteau", "el cuchillo"],
  ["la fourchette", "el tenedor"],
  ["la cuillère", "la cuchara"],
  ["l'assiette", "el plato"],
  ["le verre", "el vaso"],
  ["la tasse", "la taza"],
  ["la faim", "el hambre"],
  // Cuerpo y salud (30)
  ["le corps", "el cuerpo"],
  ["la tête", "la cabeza"],
  ["le visage", "la cara"],
  ["l'œil", "el ojo"],
  ["les yeux", "los ojos"],
  ["le nez", "la nariz"],
  ["la bouche", "la boca"],
  ["la dent", "el diente"],
  ["l'oreille", "la oreja"],
  ["les cheveux", "el pelo"],
  ["la main", "la mano"],
  ["le doigt", "el dedo"],
  ["le bras", "el brazo"],
  ["la jambe", "la pierna"],
  ["le pied", "el pie"],
  ["le genou", "la rodilla"],
  ["l'épaule", "el hombro"],
  ["le dos", "la espalda"],
  ["le ventre", "la barriga"],
  ["le cœur", "el corazón"],
  ["le sang", "la sangre"],
  ["la santé", "la salud"],
  ["la maladie", "la enfermedad"],
  ["la douleur", "el dolor"],
  ["le médecin", "el médico"],
  ["l'hôpital", "el hospital"],
  ["le médicament", "el medicamento"],
  ["fatigué", "cansado"],
  ["malade", "enfermo"],
  ["en bonne santé", "sano"],
  // Naturaleza y animales (40)
  ["la nature", "la naturaleza"],
  ["le soleil", "el sol"],
  ["la lune", "la luna"],
  ["l'étoile", "la estrella"],
  ["le ciel", "el cielo"],
  ["le nuage", "la nube"],
  ["la pluie", "la lluvia"],
  ["la neige", "la nieve"],
  ["le vent", "el viento"],
  ["l'orage", "la tormenta"],
  ["l'arbre", "el árbol"],
  ["la fleur", "la flor"],
  ["l'herbe", "la hierba"],
  ["la feuille", "la hoja"],
  ["la montagne", "la montaña"],
  ["la mer", "el mar"],
  ["la rivière", "el río"],
  ["le lac", "el lago"],
  ["la plage", "la playa"],
  ["l'île", "la isla"],
  ["la pierre", "la piedra"],
  ["le sable", "la arena"],
  ["le feu", "el fuego"],
  ["l'animal", "el animal"],
  ["le chien", "el perro"],
  ["le chat", "el gato"],
  ["l'oiseau", "el pájaro"],
  ["le cheval", "el caballo"],
  ["la vache", "la vaca"],
  ["le cochon", "el cerdo"],
  ["le lapin", "el conejo"],
  ["l'ours", "el oso"],
  ["le lion", "el león"],
  ["le singe", "el mono"],
  ["le serpent", "la serpiente"],
  ["le canard", "el pato"],
  ["la poule", "la gallina"],
  ["l'abeille", "la abeja"],
  ["le papillon", "la mariposa"],
  ["l'araignée", "la araña"],
  // Ropa (25)
  ["le vêtement", "la prenda"],
  ["la chemise", "la camisa"],
  ["le pantalon", "el pantalón"],
  ["la robe", "el vestido"],
  ["la jupe", "la falda"],
  ["le manteau", "el abrigo"],
  ["la veste", "la chaqueta"],
  ["le pull", "el suéter"],
  ["le t-shirt", "la camiseta"],
  ["le jean", "los vaqueros"],
  ["les chaussures", "los zapatos"],
  ["les chaussettes", "los calcetines"],
  ["le chapeau", "el sombrero"],
  ["les gants", "los guantes"],
  ["l'écharpe", "la bufanda"],
  ["la ceinture", "el cinturón"],
  ["le sac", "el bolso"],
  ["les lunettes", "las gafas"],
  ["le parapluie", "el paraguas"],
  ["le maillot de bain", "el traje de baño"],
  ["le pyjama", "el pijama"],
  ["les baskets", "las zapatillas deportivas"],
  ["la taille", "la talla"],
  ["le coton", "el algodón"],
  ["la laine", "la lana"],
  // Colores, números y tiempo (64)
  ["rouge", "rojo"],
  ["bleu", "azul"],
  ["vert", "verde"],
  ["jaune", "amarillo"],
  ["noir", "negro"],
  ["blanc", "blanco"],
  ["gris", "gris"],
  ["rose", "rosa"],
  ["orange", "naranja (color)"],
  ["violet", "morado"],
  ["marron", "marrón"],
  ["la couleur", "el color"],
  ["zéro", "cero"],
  ["un", "uno"],
  ["deux", "dos"],
  ["trois", "tres"],
  ["quatre", "cuatro"],
  ["cinq", "cinco"],
  ["six", "seis"],
  ["sept", "siete"],
  ["huit", "ocho"],
  ["neuf", "nueve"],
  ["dix", "diez"],
  ["vingt", "veinte"],
  ["cent", "cien"],
  ["mille", "mil"],
  ["le temps", "el tiempo"],
  ["l'heure", "la hora"],
  ["la minute", "el minuto"],
  ["la seconde", "el segundo"],
  ["le jour", "el día"],
  ["la semaine", "la semana"],
  ["le mois", "el mes"],
  ["l'année", "el año"],
  ["aujourd'hui", "hoy"],
  ["hier", "ayer"],
  ["demain", "mañana"],
  ["le matin", "la mañana"],
  ["l'après-midi", "la tarde"],
  ["le soir", "la noche"],
  ["la nuit", "la noche"],
  ["lundi", "lunes"],
  ["mardi", "martes"],
  ["mercredi", "miércoles"],
  ["jeudi", "jueves"],
  ["vendredi", "viernes"],
  ["samedi", "sábado"],
  ["dimanche", "domingo"],
  ["le printemps", "la primavera"],
  ["l'été", "el verano"],
  ["l'automne", "el otoño"],
  ["l'hiver", "el invierno"],
  ["janvier", "enero"],
  ["février", "febrero"],
  ["mars", "marzo"],
  ["avril", "abril"],
  ["mai", "mayo"],
  ["juin", "junio"],
  ["juillet", "julio"],
  ["août", "agosto"],
  ["septembre", "septiembre"],
  ["octobre", "octubre"],
  ["novembre", "noviembre"],
  ["décembre", "diciembre"],
  // Ciudad, transporte y viajes (45)
  ["la ville", "la ciudad"],
  ["le village", "el pueblo"],
  ["la rue", "la calle"],
  ["l'avenue", "la avenida"],
  ["le quartier", "el barrio"],
  ["le centre-ville", "el centro"],
  ["la place", "la plaza"],
  ["le pont", "el puente"],
  ["l'église", "la iglesia"],
  ["le musée", "el museo"],
  ["le cinéma", "el cine"],
  ["le théâtre", "el teatro"],
  ["le parc", "el parque"],
  ["la banque", "el banco"],
  ["la poste", "la oficina de correos"],
  ["la pharmacie", "la farmacia"],
  ["le magasin", "la tienda"],
  ["le marché", "el mercado"],
  ["le supermarché", "el supermercado"],
  ["la boulangerie", "la panadería"],
  ["l'hôtel", "el hotel"],
  ["la gare", "la estación"],
  ["l'aéroport", "el aeropuerto"],
  ["la voiture", "el coche"],
  ["le train", "el tren"],
  ["l'avion", "el avión"],
  ["le bus", "el autobús"],
  ["le métro", "el metro"],
  ["le vélo", "la bicicleta"],
  ["la moto", "la moto"],
  ["le bateau", "el barco"],
  ["le taxi", "el taxi"],
  ["le billet", "el billete"],
  ["le passeport", "el pasaporte"],
  ["la valise", "la maleta"],
  ["le voyage", "el viaje"],
  ["les vacances", "las vacaciones"],
  ["le plan", "el plano / el mapa"],
  ["la direction", "la dirección (rumbo)"],
  ["loin", "lejos"],
  ["près", "cerca"],
  ["à gauche", "a la izquierda"],
  ["à droite", "a la derecha"],
  ["tout droit", "todo recto"],
  ["l'arrêt", "la parada"],
  // Trabajo y escuela (35)
  ["le travail", "el trabajo"],
  ["le bureau", "la oficina"],
  ["le patron", "el jefe"],
  ["l'employé", "el empleado"],
  ["le salaire", "el salario"],
  ["la réunion", "la reunión"],
  ["le projet", "el proyecto"],
  ["l'entreprise", "la empresa"],
  ["le client", "el cliente"],
  ["le rendez-vous", "la cita"],
  ["l'école", "la escuela"],
  ["le professeur", "el profesor"],
  ["l'élève", "el alumno"],
  ["l'étudiant", "el estudiante"],
  ["le cours", "la clase"],
  ["l'examen", "el examen"],
  ["la note", "la nota"],
  ["le devoir", "la tarea"],
  ["le livre", "el libro"],
  ["le cahier", "el cuaderno"],
  ["le crayon", "el lápiz"],
  ["le stylo", "el bolígrafo"],
  ["le papier", "el papel"],
  ["la page", "la página"],
  ["le mot", "la palabra"],
  ["la phrase", "la frase"],
  ["la question", "la pregunta"],
  ["la réponse", "la respuesta"],
  ["l'erreur", "el error"],
  ["l'exemple", "el ejemplo"],
  ["la langue", "el idioma"],
  ["le sens", "el significado"],
  ["difficile", "difícil"],
  ["facile", "fácil"],
  ["important", "importante"],
  // Verbos (70)
  ["être", "ser / estar"],
  ["avoir", "tener"],
  ["faire", "hacer"],
  ["dire", "decir"],
  ["aller", "ir"],
  ["venir", "venir"],
  ["voir", "ver"],
  ["savoir", "saber"],
  ["connaître", "conocer"],
  ["vouloir", "querer"],
  ["pouvoir", "poder"],
  ["devoir", "deber"],
  ["prendre", "tomar"],
  ["donner", "dar"],
  ["manger", "comer"],
  ["boire", "beber"],
  ["dormir", "dormir"],
  ["parler", "hablar"],
  ["écouter", "escuchar"],
  ["lire", "leer"],
  ["écrire", "escribir"],
  ["apprendre", "aprender"],
  ["comprendre", "entender"],
  ["travailler", "trabajar"],
  ["jouer", "jugar"],
  ["aimer", "amar / querer"],
  ["adorer", "adorar / encantar"],
  ["détester", "odiar"],
  ["penser", "pensar"],
  ["croire", "creer"],
  ["chercher", "buscar"],
  ["trouver", "encontrar"],
  ["acheter", "comprar"],
  ["vendre", "vender"],
  ["payer", "pagar"],
  ["ouvrir", "abrir"],
  ["fermer", "cerrar"],
  ["commencer", "empezar"],
  ["finir", "terminar"],
  ["partir", "irse"],
  ["arriver", "llegar"],
  ["entrer", "entrar"],
  ["sortir", "salir"],
  ["monter", "subir"],
  ["descendre", "bajar"],
  ["rester", "quedarse"],
  ["devenir", "convertirse en"],
  ["revenir", "volver"],
  ["courir", "correr"],
  ["marcher", "caminar"],
  ["conduire", "conducir"],
  ["porter", "llevar (puesto)"],
  ["apporter", "traer"],
  ["attendre", "esperar"],
  ["aider", "ayudar"],
  ["demander", "pedir / preguntar"],
  ["répondre", "responder"],
  ["appeler", "llamar"],
  ["montrer", "mostrar"],
  ["regarder", "mirar"],
  ["choisir", "elegir"],
  ["essayer", "intentar"],
  ["utiliser", "usar"],
  ["changer", "cambiar"],
  ["continuer", "continuar"],
  ["arrêter", "parar"],
  ["oublier", "olvidar"],
  ["se souvenir", "recordar"],
  ["se lever", "levantarse"],
  ["s'habiller", "vestirse"],
  // Adjetivos y conectores (51)
  ["bon", "bueno"],
  ["mauvais", "malo"],
  ["grand", "grande"],
  ["petit", "pequeño"],
  ["nouveau", "nuevo"],
  ["vieux", "viejo"],
  ["jeune", "joven"],
  ["beau", "bonito"],
  ["joli", "lindo"],
  ["laid", "feo"],
  ["fort", "fuerte"],
  ["faible", "débil"],
  ["rapide", "rápido"],
  ["lent", "lento"],
  ["chaud", "caliente"],
  ["froid", "frío"],
  ["cher", "caro"],
  ["bon marché", "barato"],
  ["plein", "lleno"],
  ["vide", "vacío"],
  ["propre", "limpio"],
  ["sale", "sucio"],
  ["clair", "claro"],
  ["sombre", "oscuro"],
  ["heureux", "feliz"],
  ["triste", "triste"],
  ["content", "contento"],
  ["fâché", "enfadado"],
  ["calme", "tranquilo"],
  ["gentil", "amable"],
  ["méchant", "malvado"],
  ["drôle", "divertido"],
  ["sérieux", "serio"],
  ["libre", "libre"],
  ["occupé", "ocupado"],
  ["prêt", "listo"],
  ["sûr", "seguro"],
  ["possible", "posible"],
  ["impossible", "imposible"],
  ["vrai", "verdadero"],
  ["faux", "falso"],
  ["même", "mismo"],
  ["autre", "otro"],
  ["chaque", "cada"],
  ["tout", "todo"],
  ["beaucoup", "mucho"],
  ["peu", "poco"],
  ["très", "muy"],
  ["aussi", "también"],
  ["toujours", "siempre"],
  ["jamais", "nunca"],
];

const DECK_NAME = "Francés básico-intermedio";

if (WORDS.length !== 500) {
  throw new Error(`Expected 500 words, got ${WORDS.length}`);
}

const existing = db
  .query("SELECT id FROM decks WHERE name=?")
  .get(DECK_NAME) as { id: string } | null;

if (existing) {
  const count = (
    db
      .query("SELECT COUNT(*) c FROM cards WHERE deck_id=?")
      .get(existing.id) as { c: number }
  ).c;
  console.log(`Deck "${DECK_NAME}" already exists with ${count} cards — nothing to do.`);
  process.exit(0);
}

const deckId = uid();
const now = nowSec();
db.query("INSERT INTO decks(id,name,created_at) VALUES(?,?,?)").run(
  deckId,
  DECK_NAME,
  now
);

const insert = db.query(
  "INSERT INTO cards(id,deck_id,front,back,is_reversed,ease,interval_days,reps,lapses,due,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)"
);
const tx = db.transaction(() => {
  for (const [front, back] of WORDS) {
    insert.run(uid(), deckId, front, back, 0, 2.5, 0, 0, 0, now, now);
  }
});
tx();

console.log(`Seeded deck "${DECK_NAME}" with ${WORDS.length} cards.`);
