// New topic lists (not present in the original flat seeds).
// French → Spanish, German → Spanish. Nouns carry their article.
export const NEW_FR_SPORTS: [string, string][] = [
  ["le sport", "el deporte"],
  ["le football", "el fútbol"],
  ["le tennis", "el tenis"],
  ["le basket", "el baloncesto"],
  ["le match", "el partido"],
  ["l'équipe", "el equipo"],
  ["le stade", "el estadio"],
  ["le ballon", "el balón"],
  ["l'arbitre", "el árbitro"],
  ["le supporter", "el hincha"],
  ["la médaille", "la medalla"],
  ["le champion", "el campeón"],
  ["gagner", "ganar"],
  ["perdre", "perder"],
  ["faire du vélo", "montar en bicicleta"],
  ["nager", "nadar"],
  ["danser", "bailar"],
  ["chanter", "cantar"],
  ["s'entraîner", "entrenarse"],
  ["la piscine", "la piscina"],
  ["le cyclisme", "el ciclismo"],
  ["la randonnée", "el senderismo"],
  ["le film", "la película"],
  ["la musique", "la música"],
  ["la chanson", "la canción"],
  ["le jeu", "el juego"],
  ["le passe-temps", "el pasatiempo"],
  ["le loisir", "el ocio"],
  ["le week-end", "el fin de semana"],
  ["le congé", "el día libre"],
];

export const NEW_FR_SENTIMENTS: [string, string][] = [
  ["le sentiment", "el sentimiento"],
  ["l'amour", "el amor"],
  ["la haine", "el odio"],
  ["la joie", "la alegría"],
  ["la peur", "el miedo"],
  ["la colère", "la ira"],
  ["l'espoir", "la esperanza"],
  ["joyeux", "alegre"],
  ["malheureux", "infeliz"],
  ["épuisé", "agotado"],
  ["fier", "orgulloso"],
  ["jaloux", "celoso"],
  ["nerveux", "nervioso"],
  ["détendu", "relajado"],
  ["courageux", "valiente"],
  ["timide", "tímido"],
  ["inquiet", "preocupado"],
  ["soulagé", "aliviado"],
  ["surpris", "sorprendido"],
  ["déçu", "decepcionado"],
  ["amoureux", "enamorado"],
  ["reconnaissant", "agradecido"],
  ["ennuyé", "aburrido"],
  ["stressé", "estresado"],
  ["patient", "paciente"],
];

export const NEW_FR_PROFESSIONS: [string, string][] = [
  ["le métier", "la profesión"],
  ["l'ingénieur", "el ingeniero"],
  ["le cuisinier", "el cocinero"],
  ["le chauffeur", "el conductor"],
  ["le vendeur", "el vendedor"],
  ["le policier", "el policía"],
  ["l'agriculteur", "el agricultor"],
  ["l'écrivain", "el escritor"],
  ["l'artiste", "el artista"],
  ["le boulanger", "el panadero"],
  ["le coiffeur", "el peluquero"],
  ["le plombier", "el fontanero"],
  ["l'électricien", "el electricista"],
  ["le pompier", "el bombero"],
  ["le soldat", "el soldado"],
  ["le pilote", "el piloto"],
  ["le juge", "el juez"],
  ["l'avocat", "el abogado"],
  ["le journaliste", "el periodista"],
  ["le photographe", "el fotógrafo"],
  ["l'infirmier", "el enfermero"],
  ["le dentiste", "el dentista"],
  ["le vétérinaire", "el veterinario"],
  ["le directeur", "el director"],
  ["le comptable", "el contable"],
];

export const NEW_DE_KLEIDUNG: [string, string][] = [
  ["die Kleidung", "la ropa"],
  ["das Hemd", "la camisa"],
  ["die Hose", "el pantalón"],
  ["das Kleid", "el vestido"],
  ["der Rock", "la falda"],
  ["der Mantel", "el abrigo"],
  ["die Jacke", "la chaqueta"],
  ["der Pullover", "el suéter"],
  ["das T-Shirt", "la camiseta"],
  ["die Jeans", "los vaqueros"],
  ["die Schuhe", "los zapatos"],
  ["die Socken", "los calcetines"],
  ["der Hut", "el sombrero"],
  ["die Handschuhe", "los guantes"],
  ["der Schal", "la bufanda"],
  ["der Gürtel", "el cinturón"],
  ["die Tasche", "el bolso"],
  ["die Brille", "las gafas"],
  ["der Regenschirm", "el paraguas"],
  ["der Badeanzug", "el traje de baño"],
];

export const NEW_DE_FARBEN: [string, string][] = [
  ["rot", "rojo"],
  ["blau", "azul"],
  ["grün", "verde"],
  ["gelb", "amarillo"],
  ["schwarz", "negro"],
  ["weiß", "blanco"],
  ["grau", "gris"],
  ["rosa", "rosa"],
  ["türkis", "turquesa"],
  ["lila", "morado"],
  ["braun", "marrón"],
  ["die Farbe", "el color"],
  ["null", "cero"],
  ["vier", "cuatro"],
  ["fünf", "cinco"],
  ["sechs", "seis"],
  ["sieben", "siete"],
  ["acht", "ocho"],
  ["neun", "nueve"],
  ["zwanzig", "veinte"],
];

export const NEW_DE_SPORT: [string, string][] = [
  ["der Sport", "el deporte"],
  ["der Fußball", "el fútbol"],
  ["das Spiel", "el juego"],
  ["die Mannschaft", "el equipo"],
  ["gewinnen", "ganar"],
  ["verlieren", "perder"],
  ["laufen", "correr"],
  ["schwimmen", "nadar"],
  ["das Schwimmbad", "la piscina"],
  ["das Fahrrad", "la bicicleta"],
  ["wandern", "hacer senderismo"],
  ["das Hobby", "el pasatiempo"],
  ["der Film", "la película"],
  ["das Kino", "el cine"],
  ["die Musik", "la música"],
  ["das Lied", "la canción"],
  ["tanzen", "bailar"],
  ["singen", "cantar"],
  ["spielen", "jugar"],
  ["das Wochenende", "el fin de semana"],
];

export const NEW_DE_BERUFE: [string, string][] = [
  ["der Beruf", "la profesión"],
  ["der Lehrer", "el profesor"],
  ["der Arzt", "el médico"],
  ["der Ingenieur", "el ingeniero"],
  ["der Koch", "el cocinero"],
  ["der Fahrer", "el conductor"],
  ["der Verkäufer", "el vendedor"],
  ["der Polizist", "el policía"],
  ["der Bauer", "el agricultor"],
  ["der Schriftsteller", "el escritor"],
  ["der Künstler", "el artista"],
  ["der Student", "el estudiante"],
  ["der Kellner", "el camarero"],
  ["der Friseur", "el peluquero"],
  ["der Job", "el trabajo"],
];

export const NEW_DE_GEFUEHLE: [string, string][] = [
  ["das Gefühl", "el sentimiento"],
  ["die Liebe", "el amor"],
  ["der Hass", "el odio"],
  ["die Freude", "la alegría"],
  ["die Angst", "el miedo"],
  ["die Wut", "la rabia"],
  ["die Hoffnung", "la esperanza"],
  ["glücklich", "feliz"],
  ["traurig", "triste"],
  ["müde", "cansado"],
  ["stolz", "orgulloso"],
  ["eifersüchtig", "celoso"],
  ["nervös", "nervioso"],
  ["ruhig", "tranquilo"],
  ["mutig", "valiente"],
];
